name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/jigsaw-blog

jobs:
  build-and-push:
    environment: live
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Build the Docker Image
        run: docker build -t $REPOSITORY .

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Publish the Builded Image
        run: docker push $REPOSITORY

      - name: Update README File
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: $REPOSITORY
          readme-filepath: ./README.md

      - name: Remove Docker Credentials
        run: docker logout
