name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Build the Docker Image
        run: docker build -t jigsaw-blog .

  publish:
    environment: live
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Publish the Builded Image
        run: docker push davigsilva/jigsaw-blog

      - name: Remove Docker Credentials
        run: docker logout
